kind: pipeline
type: docker
name: default


steps:
  - name: build_image
    image: docker
    volumes:
      - name : build_docker
        path: /var/run/docker.sock
    commands :
      - docker build docker/ -t ubuntu_docker

  - name: cmake_generation
    image: ubuntu_docker
    pull: never
    commands:
      - mkdir build || exit 0
      - cd build
      - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SAMPLES=ON -DBUILD_DOCUMENTATION=ON ..

  - name: build
    image: ubuntu_docker
    pull : never
    commands:
      - mkdir build || exit 0
      - cd build
      - cmake --build . -j 10


volumes:
  - name: build_docker
    host:
      path: /var/run/docker.sock